### ISSUE TITLE
Explorer Title Background isn't working well.

### ISSUE THREAD

**Issue by NullGang** [Night-Star04/vscode-fluent-ui#8]
![{5904BEFE-9ECD-4938-AF64-8AF3EB87C292}](https://github.com/user-attachments/assets/99b34981-51df-4b66-92e4-52666e58c7d6)

**Comment by NullGang** [comment]
how do I  change it?

**Comment by Night-Star04** [comment]
Hi @NullGang,

Thanks for pointing this out! I'll be working on fixing the effect in the next few days. I'll let you know if there are any updates.
